[connections.my_database]
    type="sql"
    dialect="mysql"
    username="root"
    password="lmmlmm19980323"
    host="127.0.0.1" # IP or URL
    port=3306 # Port number
    database="data_learn" # Database name