wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.2
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725286692
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 3
      - 23
      4: 3.11.0
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
